### ISSUE TITLE
无法在 gcc 编译器上编译

### ISSUE THREAD

**Issue by oyiadin** [Emmettwoo/simple_todo#1]
=。=用了好多 VS 专用函数，对 gcc 真不友好

**Comment by Emmettwoo** [comment]
Ծ ̮ Ծ因为想学习使用VS2010来着，据说二级C用这个环境。很多函数都变形为_s，增加了防止溢出的安全机制。

**Comment by oyiadin** [comment]
计科考 c 没啥用 在我看来就相当于英语专业去考四级
反正我不考

**Comment by oyiadin** [comment]
至于 _s 们，你应该知道 scanf("%10s"); strncpy, strncat

**Comment by Emmettwoo** [comment]
哈哈，其实C我都觉得虚，总得先拿个证书意思意思一下，我是这么觉得。
然后scanf这个用法还真没想到，只在数字上用过，果然我还是too young。
strncpy的话，emmm……有道理，VS2010引导我用的_s我以为会是最优解2333所以没考虑太多。
谢谢(*^_^*)，会试试修改然后用gcc编译的，等把目前在写的一个功能写完。

**Comment by Emmettwoo** [comment]
临时提交了新版本，测试通过支持gcc编译，并且提供了Makefile。
（不过Loop功能写一半，所以这个版本没有更新版本号，代码有部分loop乱入哈哈）

**Comment by oyiadin** [comment]
我还不会写 Makefile 来着…
